### ISSUE TITLE
not update customer.discount when assign a coupon to customer

### ISSUE THREAD

**Issue by conwqi1** [rebelidealist/stripe-ruby-mock#155]
when assign a coupon id to customer, (Stripe::Customer.retrieve("id").coupon="coupon_id"). It should update the Stripe::Customer.retrieve("id").discount. However, Stripe::Customer.retrieve("id").discount = null.

**Comment by alexmamonchik** [comment]
+1

**Comment by alexmamonchik** [comment]
@conwqi1 [fixed] (https://github.com/rebelidealist/stripe-ruby-mock/blob/master/spec/shared_stripe_examples/customer_examples.rb#L156-L165)
