### ISSUE TITLE
Can't retrieve balance transaction

### ISSUE THREAD

**Issue by iamtheschmitzer** [rebelidealist/stripe-ruby-mock#158]
When I add to my charge.succeeded webhook handler 

`if bt = Stripe::BalanceTransaction.retrieve(charge.balance_transaction)`

I see the error in stdout

WARNING: Unrecognized method + url: [get /v1/balance/history/test_txn_1]

I've set up the charge like this

`    charge = Stripe::Charge.create({ amount: 300 })
    event = StripeMock.mock_webhook_event('charge.succeeded', {
      id: charge.id,
      amount: charge.amount,
      balance_transaction: charge.balance_transaction
    })`

Am I setting it up incorrectly, or is the balance transaction not supported?

**Comment by omederos** [comment]
I'm having the same issue here... StripeMock doesn't create the balance transactions when capturing some card?

**Comment by hayesr** [comment]
I don't think this is covered yet and requires a new handler. I started looking into doing this last night, but saw some indication that the work might have been started. ([Referring to this](https://github.com/rebelidealist/stripe-ruby-mock/blob/master/lib/stripe_mock/instance.rb#L114))

Perhaps @EddM or someone from @rebelidealist can give insight on what needs to be done for this?

**Comment by kaspergrubbe** [comment]
This would be very helpful to have mocked. Thanks for looking into it.

**Comment by kevinansfield** [comment]
Just ran into this too. Is there any workaround at the moment?

**Comment by IanVaughan** [comment]
I'm still getting this error, is that expected?
I appreciate the call for contributors, and thus it may still be an issue, I just wanted to know if its just me.

**Comment by kevinansfield** [comment]
Yes, I believe that's still expected. I stubbed the response out where I needed it:

```
  let(:balance_stub) {
    OpenStruct.new(
      amount: 44803,
      fee: 1499,
      currency: 'nok'
    )
  }

  it 'does something' do
    Stripe::BalanceTransaction.stub :retrieve, balance_stub do
      res, op = Sale::Create.run(create_params)
    end
  end  
```

**Comment by xn** [comment]
Current rspec syntax:
```expect(Stripe::BalanceTransaction).to receive(:retrieve).and_return(balance_stub)```

**Comment by iamtheschmitzer** [comment]
Closing issue, handler exists now
