### ISSUE TITLE
Customers.invoice returns array, not Stripe::ListObject

### ISSUE THREAD

**Issue by kareem** [rebelidealist/stripe-ruby-mock#160]
When I get a customer's invoices from the Stripe API, I get this:

`irb(main):009:0> c.invoices`

`=> #<Stripe::ListObject:0x3fc89d49b1a0> JSON: {
  "object": "list",
  "has_more": true,
  "url": "/v1/invoices",
  "data": [ Array_of_Stripe::Invoice_objects]
}`

When I get a customer's invoices from this mocking gem, I get:

`(rdb:1) pp @stripe_customer.invoices`

`[#<Stripe::Invoice:0x3fd8455a50ac id=test_in_3> JSON: {
  "id": "test_in_3",
  "date": 1349738950,
  "period_end": 1349738950,
  "period_start": 1349738950,
  "lines": {"object":"list","count":1,"url":"/v1/invoices/test_in_3/lines","data":[{"id":"ii_test","object":"line_item","type":"invoiceitem","livemode":false,"amount":1000,"currency":"usd","proration":false,"period":{"start":1349738920,"end":1349738920},"quantity":null,"plan":null,"description":"Test invoice item","metadata":{}}]},
  "subtotal": 1000,
  "total": 1000,
  "customer": "stripe_customer_id_1",
  "object": "invoice",
  "attempted": false,
  "closed": false,
  "paid": false,
  "livemode": false,
  "attempt_count": 0,
  "amount_due": 1000,
  "currency": "usd",
  "starting_balance": 0,
  "ending_balance": null,
  "next_payment_attempt": 1349825350,
  "charge": null,
  "discount": null,
  "subscription": null
}`

Note the difference; the API returns a `Stripe::ListObject`, while the mocking gem returns an array of `Stripe::Invoices`.

The problem is that my code assumes the `StripeInvoices` are in the `Stripe::ListObject.data` array, so I can't write tests against this part of my code.

**Comment by EddM** [comment]
Just FYI to those who read this, PR #151 should address this

**Comment by EddM** [comment]
Fixed in #172
