### ISSUE TITLE
Stripe::Charge.all should handle `starting_after` and `ending_before` params

### ISSUE THREAD

**Issue by destroytoday** [rebelidealist/stripe-ruby-mock#174]
The latest API has two params to use as cursors: https://stripe.com/docs/api/ruby#list_charges

`offset` no longer exists.

**Comment by destroytoday** [comment]
Alos, `Stripe::Charge.all` should return ListObject.

**Comment by EddM** [comment]
Thanks for this! However, this should be fixed very soon with #172
