### ISSUE TITLE
Missing "forgiven" parameter in Invoices

### ISSUE THREAD

**Issue by TrevorHinesley** [rebelidealist/stripe-ruby-mock#175]
Per Stripe's documentation, there is now a `forgiven` boolean denoting whether an unpaid invoice has been forgiven or not.

https://stripe.com/docs/api#invoice_object

**Comment by EddM** [comment]
Was this property added recently? Or has it simply always been there?

**Comment by TrevorHinesley** [comment]
Good question, I just assumed recent since it wasn't in the mock library. You may be correct. I just can't test invoices without it so I thought I'd post it here, haven't had much time lately to contribute it myself, in case anyone gets a second to drop it in!

**Comment by theoretick** [comment]
It looks like its just missing.  I checked back to a [2011-01-01 API response and it was still present](https://gist.github.com/theoretick/181ecd5f40595e2ea650)
