### ISSUE TITLE
Customer needs to have source instead of card now

### ISSUE THREAD

**Issue by TrevorHinesley** [rebelidealist/stripe-ruby-mock#189]
Stripe has made a pretty major change to how customers cards and/or other payment sources are set and retrieved. Charge and default_charge have been swapped with source and default_source, respectively. Which, if you allow more payment types than just cards, returns a list of different payment types rather than one. See https://stripe.com/docs/upgrades

**Comment by TrevorHinesley** [comment]
This also applies to anywhere `.card` is used, it looks like. For instance, `charge.card` is now `charge.source`, setting `subscription.card` is now done as `subscription.source = token`, etc. Might be worth an audit. It can be kept backwards compatible by simply allowing card/cards/default_card to be source/sources/default_source anywhere they are used.

**Comment by nhocki** [comment]
FWIW I've started working on a PR for this.. any help is appreciated.

**Comment by elilux** [comment]
@nhocki me too. Here's what I have so far. Want to branch off this or do you have some local commits? https://github.com/rebelidealist/stripe-ruby-mock/compare/master...elilux:master

**Comment by nhocki** [comment]
@elilux I've just opened #191 ... I saw your comment too late into the development of that ... I did notice some problems between the Stripe API docs and the gem (stripe/stripe-ruby#215) so for now this has both endpoints.

**Comment by elilux** [comment]
@nhocki looks good. Would be great to get this merged.
