### ISSUE TITLE
Stripe::Customer.create does not include a default_source

### ISSUE THREAD

**Issue by zhaohanweng** [rebelidealist/stripe-ruby-mock#198]
```
customer = Stripe::Customer.create({
  email: 'johnny@appleseed.com',
  card: stripe_helper.generate_card_token
})
```

running the basic test example in the README, this `customer` does not have any default_source, also the `sources.data` field is empty. 
But when I look at the code, https://github.com/rebelidealist/stripe-ruby-mock/blob/38b4a31e93844b991675b7298d564ea03edc253f/spec/shared_stripe_examples/customer_examples.rb#L17 I see the sources should be returned.

**Comment by zhaohanweng** [comment]
Sorry, I see the difference. The card field now is changed to `source` in the `create`. Just have to update the README. closing this.

**Comment by gkop** [comment]
@zhaohanweng thanks for this! Fwiw the README still says `card` :( In the first code block under https://github.com/rebelidealist/stripe-ruby-mock#description
