### ISSUE TITLE
Nil api key causing exception with Stripe 1.20.4

### ISSUE THREAD

**Issue by crberube** [rebelidealist/stripe-ruby-mock#209]
Wanted to point out this issue that I noticed even though stripe-ruby-mock is only supporting stripe 1.20.1 as of now.

As of the following PR https://github.com/stripe/stripe-ruby/pull/221 stripe raises a TypeError when it receives an api_key in the options that is not a string. In the mock_request method of StripeMock::Instance, api_key is a required parameter that is nil by default, thus raising an exception unless an api key is explicitly passed.

As an example, the following code raises a TypeError:
```ruby
stripe_customer.sources.create(card: stripe_token)
```

while this code works as expected:
```ruby
stripe_customer.sources.create({card: stripe_token}, {api_key: Stripe.api_key})
```

**Comment by DanielePalombo** [comment]
same problem

**Comment by aliou** [comment]
Having the same problem.

**Comment by jasonrhalpern** [comment]
I think I have a somewhat similar problem. In various methods in my code I use things like: 

customer.subscriptions.retrieve({SUB_ID})
customer.sources.retrieve({CARD_ID})

I am using this gem to test the methods that then make these API calls to Stripe. The ones for create customer/subscription/plan are working fine without the api_key, but all of the calls to the retrieve methods (listed above) are failing with the following error:

TypeError: api_key must be a string.

**Comment by micahwedemeyer** [comment]
+1 same problem

**Comment by jb41** [comment]
Anyone found solution to that?

**Comment by jasonrhalpern** [comment]
I still haven't figured out a solution to that issue.

**Comment by samkpower** [comment]
+1

**Comment by psiedlak** [comment]
+1

**Comment by moneytree-doug** [comment]
:+1:

**Comment by justinbburris** [comment]
@jasonrhalpern

Similar to what @crberube mentioned, you can (for now) make your call with the api_key

```ruby
stripe_customer.sources.retrieve(stripe_card_id, {api_key: Stripe.api_key})
```

**Comment by alexmamonchik** [comment]
you can use branch https://github.com/rebelidealist/stripe-ruby-mock/tree/stripe-1.21.0

**Comment by jasonrhalpern** [comment]
Thanks for the help on this guys, I'll probably use the older branch for the time being. I don't really want to have to modify the stripe code that I am testing by adding the api_key since doing so would only be necessary for the tests to pass and not for the actual implementation.

**Comment by moneytree-doug** [comment]
@alexmamonchik Is this fix in the roadmap? I can go change all my tests to use the syntax suggested by @crberube , but that doesn't seem to be a long term solution.

**Comment by alexmamonchik** [comment]
@moneytree-doug `master` use Stripe 1.20.1 because 1.21.0 includes changes that breaks a lot of tests. In this branch I'm trying to fix all breaks. If it'll have compatibility with 1.20.1 we are going to merge it with `master`. Will be fine if you start using this branch and add issues about bugs you found.

**Comment by esbanarango** [comment]
+1 Same problem here with `'stripe', '~> 1.31.0'` and `'stripe-ruby-mock', '~> 2.2.0'`.
I was able to "fix" it by setting a random string to the `api_key ` before starting `StripeMock`.

````ruby

  let(:stripe_helper) { StripeMock.create_test_helper }
  before do 
    Stripe.api_key = 'blablabla'
    StripeMock.start
  end
  after { StripeMock.stop }

**Comment by ometa** [comment]
+1
Same problem here with `'stripe', '~> 1.31.0'` and `'stripe-ruby-mock', '~> 2.2.1'`.
I successfully used the workaround mentioned by @esbanarango, thank you!

**Comment by HunterMeyer** [comment]
+1

**Comment by alexmamonchik** [comment]
@HunterMeyer try to get code from repo instead of rubygems
