### ISSUE TITLE
Bundler could not find compatible versions for gem "stripe"

### ISSUE THREAD

**Issue by tirdadc** [rebelidealist/stripe-ruby-mock#215]
The current stripe gem is 1.20.4 and there seems to be a dependency on 1.20.1 in the latest version of this gem:

```
In Gemfile:
    stripe-ruby-mock (~> 2.1.1) ruby depends on
      stripe (= 1.20.1) ruby

    stripe (1.20.4)
```

This currently prevents installation.

**Comment by maxgronlund** [comment]
I'm having the same issue

**Comment by hayesr** [comment]
I believe the version was locked until compatibility with newer versions of Stripe can be worked out.

**Comment by sungwoncho** [comment]
I am using stripe (1.21.0) and have the same issue.

**Comment by alexmamonchik** [comment]
newest version of stripe - 1.21.0. We have branch `stripe-1.21.0` because new Stripe contains breaking changes. I recommend  switch to new branch or wait merging 1.21.0 to master.

**Comment by louim** [comment]
Is there something specific blocking us from merging the `stripe-1.21.0` branch into master, unlock the Stripe gem and release a new version? I would like to use the latest version of the Stripe Gem. 

Happy to help if there is anything that can be done to make it happen. :smile:

**Comment by alexmamonchik** [comment]
@louim Stripe has new version of API. And merge newest branch breaks a lot of tests. Many developers use old version.

**Comment by louim** [comment]
@alexmamonchik I understand this. I will test the branch, however, I thought it had been created specifically to patch the bugs with the new version of the Stripe API. 

On the other hand, that's what semantic versioning is for. Rolling a new version of the gem supporting the newest Stripe API should be done once the tests are passing. People can alway lock to the gem version that correspond to their older API version.

**Comment by alexmamonchik** [comment]
you right. That what I want. I started new branch (`stripe-1.21.0`, Stripe has more versions) but didn't finish yet. Any new PR from you helps, welcome. Current gem locked to `1.20.1` because version 1.20.3 and newest break most of tests. `stripe-1.21.0` is not ready to merge, sorry. @kathyonu is working on this branch. Thanks to all developers. I'll join you when I have more free time.

**Comment by juanpastas** [comment]
Stripe gem is now 1.22, should I use 1.21 branch?

**Comment by louim** [comment]
@juanpastas Stripe gem is now 1.26. I have a running version locally with the spec fixed, I plan on doing a pull request soon.

**Comment by juanpastas** [comment]
Thanks. Do you have that in a public repo?

**Comment by alexmamonchik** [comment]
@juanpastas  before updating to 1.26 I decided to update to 1.21. I still haму errors with charge tests.@louim also is working on this branch - very thanks. I'll continue soon when I have more free time.

**Comment by louim** [comment]
@juanpastas @alexmamonchik the PR is up #259

**Comment by alexmamonchik** [comment]
@louim thanks!

**Comment by alexmamonchik** [comment]
Hi All! Big update:
- new release of gem 2.2.0
- now support stripe 1.27.1
