### ISSUE TITLE
Creating Customer with Card hash as source raises InvalidRequestError

### ISSUE THREAD

**Issue by sico** [rebelidealist/stripe-ruby-mock#226]
According to the latest Stripe docs, I should be able to create a Customer using a dictionary of card values as the `source` param. But, this doesn't seem to work in the latest mock:

`Stripe::Customer.create(source: {object: 'card', number: 4242424242424242, exp_month: 12, exp_year: 24}, email: 'blah@blah.com')`
Results in 
`Stripe::InvalidRequestError: Invalid token id: {:object=>"card", :number=>4242424242424242, :exp_month=>12, :exp_year=>24}`

Should this be working?

**Comment by alexmamonchik** [comment]
@sico fixed. Soon @mindeavor will make release of gem, but you can use `master` branch now.

**Comment by sico** [comment]
Perfect, thanks!
