### ISSUE TITLE
Error While Paginating

### ISSUE THREAD

**Issue by TheBerg** [rebelidealist/stripe-ruby-mock#230]
So I am executing this code:

```
Stripe::Charge.all({transfer_id: stripe_id, starting_after: starting_after }, organization.stripe_access_token)
```

And when it runs I get this error on `list.rb:43`:
```
undefined method `id' for #<Hash:0x007feb67ac5300>
```

If I monkey patch that line to be `datum[:id]` instead of `datum.id`, it works fine.

Am I doing something wrong or is this a bug?

FYI: To populate the Stripe::Charge Mocks I run:

```
    before do
      100.times do
        Stripe::Charge.create(transfer_id: stripe_transfer.id, amount: 100, currency: "usd")
      end
    end
```

**Comment by alexmamonchik** [comment]
@TheBerg fixed. But I don't understand `Stripe::Charge.create(transfer_id: stripe_transfer.id...` maybe you mean `customer` instead of `transfer_id` ?

**Comment by TheBerg** [comment]
Thanks!

Re `transfer_id`: I am creating a summary report of every transfer that is deposited to our customers accounts.
