### ISSUE TITLE
Stripe CardError does not seem to be set up correctly

### ISSUE THREAD

**Issue by georgeu2000** [rebelidealist/stripe-ruby-mock#246]
According to [Stripe Docs](https://stripe.com/docs/api/ruby#errors), 

    rescue Stripe::CardError => e
      # Since it's a decline, Stripe::CardError will be caught
      body = e.json_body
      err  = body[:error]

In spec:

    StripeMock.prepare_card_error( :card_declined, :new_charge )

The issue is that `e.json_body` is `nil`.

**Comment by gvc** [comment]
:+1:
