### ISSUE TITLE
Stripe::InvalidRequestError Exception: You must supply a valid card error with subscriptions

### ISSUE THREAD

**Issue by sebastiandeutsch** [rebelidealist/stripe-ruby-mock#250]
Attaching a subscription directly in the create method gives an "Stripe::InvalidRequestError Exception: You must supply a valid card" error:

    Stripe::Customer.create(description: @user.full_name, email: @user.email , plan: @subscription.plan_stripe_id, card: @payment.stripe_card_token)

If I create the customer directly:

    customer = Stripe::Customer.create(description: @user.full_name, email: @user.email, card: @payment.stripe_card_token)

everything works. The only difference is that I passed a plan to the create method.

**Comment by alexmamonchik** [comment]
@sebastiandeutsch  use `source` instead of `card`

**Comment by sebastiandeutsch** [comment]
@alexmamonchik it works thanks.
