### ISSUE TITLE
How would one test for failed charges?

### ISSUE THREAD

**Issue by mdere** [rebelidealist/stripe-ruby-mock#267]
So I did the following:

```
      before(:each) do

        failed_card_num = '4000000000000002'

        failed_customer = Stripe::Customer.create(
          source: StripeMock.generate_card_token(
            number: failed_card_num,
            brand: 'Visa'
          )
        )

        failed_card_token = Stripe::Token.create(
          :customer => failed_customer.id,
          :source => failed_customer.sources.first.id
        )

        @failed_charge = Stripe::Charge.create(source: failed_card_token.id, amount: @amount, currency: "usd")
      end

      it 'expects to return false once if status of the charge failed' do
        # expect(is_a_valid_charge?(@failed_charge)).to eq false
      end
```

Where the valid_charge method checks if status is "succeed" - if not return false.  So the card num above I assumed would do the trick. Any idea what I can do ?

**Comment by kathyonu** [comment]
@mdere Does this help ?
```ruby
require 'stripe_mock'
describe 'Card Error Prep' do
  it 'prepares a card error', live: true do
    StripeMock.start
    StripeMock.prepare_card_error(:card_declined, :new_charge)
    cus = Stripe::Customer.create(email: 'alice@example.com')
    expect(cus.id).to match(/^test_cus/)
    expect { Stripe::Charge.create(
      amount: 900,
      currency: 'usd',
      source: StripeMock.generate_card_token(number: '4242424242424241'),
      description: 'hello'
      )
    }.to raise_error(Stripe::CardError, 'The card was declined')
    StripeMock.stop
  end
end
```

**Comment by mdere** [comment]
@kathyonu - Well, the thing with my method "is_a_valid_charge" takes in a charge object and checks if the charge is failed by confirming the status of the charge object it self. 

I see that the charge is created with almost the same exact replica of the live charge object, but I am looking for if it is possible to mimc a charge object when it fails so I can access the status of "failed".

**Comment by kathyonu** [comment]
Stripe returns an error if the card is declined, not a full bodied response as when charge succeeds.  
Stripe ref: Within [Create a charge](https://stripe.com/docs/api#create_charge) is a paragraph titled,

__Returns__

"Returns a charge object if the charge succeeded. Raises an [error](https://stripe.com/docs/api#errors) if something goes wrong. A common source of error is an invalid or expired card, or a valid card with insufficient available balance."

This means there is no object response given on a failure.  You cannot test that which does not exist in their response.  Have I understood the issue correctly, and ..

Does this resolve the issue ?

**Comment by mdere** [comment]
@kathyonu - Interesting, well the reason why I'm implementing this is that we noticed various charges that were created on our dashboard that didn't go through and saw that they failed. I def can pull the charges via Charge.retrieve that failed and shows a status of failed.

**Comment by kathyonu** [comment]
There's the answer.  Well done.

**Comment by kathyonu** [comment]
@mdere Should this Issue be closed ?

**Comment by mdere** [comment]
We are good - thanks!

On Fri, Oct 16, 2015 at 1:55 PM, kathyonu <notifications@github.com> wrote:

> @mdere <https://github.com/mdere> Should this Issue be closed ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebelidealist/stripe-ruby-mock/issues/267#issuecomment-148785411>
> .
>



-- 

*Michael Dere*

*Mobile : (206) 779-4838*


*Email : michael.dere@gmail.com <michael.dere@gmail.com>*
