### ISSUE TITLE
create Stripe::Refund returned a object Stripe::StripeObject rather than Stripe::Refund object

### ISSUE THREAD

**Issue by chenghung** [rebelidealist/stripe-ruby-mock#273]
[StripeMock] Warning : Unrecognized endpoint + method : [post /v1/refunds]
[StripeMock] params: {:charge=>"test_ch_4"}

create Stripe::Refund returned a object Stripe::StripeObject rather than Stripe::Refund object
this broken our testcases.

**Comment by hayesgm** [comment]
Experiencing this issue as well

**Comment by hayesgm** [comment]
I worked around this issue by mocking a refund object by hand:

```ruby
expect(Stripe::Refund).to receive(:create).and_return(Stripe::Refund.new(id: "refund_123"))
```

**Comment by andytcox** [comment]
I've been experiencing this same problem, but only in some tests. It seems as if https://github.com/rebelidealist/stripe-ruby-mock/issues/273 is related, with all of these it seems like base stripe objects(`StripeObject`) are not getting converted into their proper classes(in this case `Stripe::Refund`). So far all my efforts to find out why this happens or why its on certain tests have yielded nothing.

**Comment by michaeldever** [comment]
Experiencing this issue too.

**Comment by jorge-d** [comment]
Same happens to me, steps to reproduce:
```
$ require 'stripe_mock'
$ StripeMock.start

$ customer = Stripe::Customer.create({
  email: 'random@email.com',
  card: StripeMock.create_test_helper.generate_card_token
})

$ charge =  Stripe::Charge.create(
  amount: 1000,
  currency: 'eur',
  customer: customer.id
)

$ refund = Stripe::Refund.create(
  charge: charge.id,
  amount: 500,
)

=> [StripeMock] Warning : Unrecognized endpoint + method : [post /v1/refunds]
=> [StripeMock] params: {:charge=>"test_ch_6", :amount=>500}

$ refund.class
=> Stripe::StripeObject
```
