### ISSUE TITLE
saving a Stripe::Customer makes subscriptions unusable

### ISSUE THREAD

**Issue by aharbick** [rebelidealist/stripe-ruby-mock#274]
stripe-ruby-mock (2.2.0)
stripe (1.31.0)
api_version: '2015-10-16'

If I create a stripe customer like so:
```
(byebug) sc = Stripe::Customer.create
#<Stripe::Customer:0x3fc862a48408 id=test_cus_6> JSON: {
  "id" : "test_cus_6",
  "email" : "stripe_mock@example.com",
  "description" : "an auto-generated stripe customer data mock",
  "object" : "customer",
  "created" : 1372126710,
  "livemode" : false,
  "delinquent" : false,
  "discount" : null,
  "account_balance" : 0,
  "sources" : {
    "object" : "list",
    "total_count" : 0,
    "url" : "/v1/customers/test_cus_6/sources",
    "data" : []
  },
  "subscriptions" : {
    "object" : "list",
    "total_count" : 0,
    "url" : "/v1/customers/test_cus_6/subscriptions",
    "data" : []
  },
  "default_source" : null
}
```

and then save it like so...
```
(byebug) sc.save
#<Stripe::Customer:0x3fc862a48408 id=test_cus_6> JSON: {
  "id" : "test_cus_6",
  "email" : "stripe_mock@example.com",
  "description" : "an auto-generated stripe customer data mock",
  "object" : "customer",
  "created" : 1372126710,
  "livemode" : false,
  "delinquent" : false,
  "discount" : null,
  "account_balance" : 0,
  "sources" : {},
  "subscriptions" : {},
  "default_source" : null
}
```

The subscriptions are no longer usable as in something like this:
```
(byebug) sc.subscriptions.create(plan: 'bw-standard')
*** NoMethodError Exception: undefined method `create' for #<Stripe::StripeObject:0x3fc862a397dc> JSON: {}
```

What am I doing wrong?

**Comment by aharbick** [comment]
Possibly related to #263

**Comment by alexmamonchik** [comment]
Hi

Does code below break your tests? Or maybe this example is wrong? I see subscription list object before and after save.
```ruby
      customer = Stripe::Customer.create(id: 'lolwhat')
      puts customer.inspect
      customer.description = 'llll'
      puts customer.save.inspect
      customer.subscriptions.create(plan: plan.id)
      puts customer.inspect
```

**Comment by aharbick** [comment]
Just to state the obvious...  The above code WILL work as expected when in a normal development environment OR when StripeMock isn't in play.  But....  If you change your example to include:

```
StripeMock.start
```

Then this is what the above code would kick out:

```
#<Stripe::Customer:0x3ff596216300 id=lolwhat> JSON: {
  "id" : "lolwhat",
  "email" : "stripe_mock@example.com",
  "description" : "an auto-generated stripe customer data mock",
  "object" : "customer",
  "created" : 1372126710,
  "livemode" : false,
  "delinquent" : false,
  "discount" : null,
  "account_balance" : 0,
  "sources" : {
    "object" : "list",
    "total_count" : 0,
    "url" : "/v1/customers/lolwhat/sources",
    "data" : []
  },
  "subscriptions" : {
    "object" : "list",
    "total_count" : 0,
    "url" : "/v1/customers/lolwhat/subscriptions",
    "data" : []
  },
  "default_source" : null
}
#<Stripe::Customer:0x3ff596216300 id=lolwhat> JSON: {
  "id" : "lolwhat",
  "email" : "stripe_mock@example.com",
  "description" : "llll",
  "object" : "customer",
  "created" : 1372126710,
  "livemode" : false,
  "delinquent" : false,
  "discount" : null,
  "account_balance" : 0,
  "sources" : {},
  "subscriptions" : {},
  "default_source" : null
}
```

and the problem is that in Stripe::APIOperations::Update::save they call serialize_params and then initialize_from which turns the subscriptions into a plain old hash.

The pull request for #266 is close to making it work however the check on params[:subscriptions][:data].nil? isn't a sufficient check for "empty"

Because the above code, I believe is passing in a params that looks something like:
```
{:subscriptions => {:data => [{}]}}
```

Sorry I wasn't able to dig deeper into how the underlying mechanics works.

FWIW...  Downgrading to ruby-stripe-mock 2.1.1 (which pulls in stripe 1.20.1) resolves the problem and all of my tests pass as expected.

**Comment by booleanbetrayal** [comment]
Running into the same issue (hi @aharbick !).

**Comment by aharbick** [comment]
Fancy meeting you here @booleanbetrayal ! ;)

**Comment by alexmamonchik** [comment]
@aharbick Yes, I found your error. Did you use gem 2.20 from rubygems or from github?

**Comment by aharbick** [comment]
rubygems, but FWIW, I also tried to pull from master on github (to see if the #266 pull request solves the issue)

```
gem 'stripe-ruby-mock', git: https://github.com/rebelidealist/stripe-ruby-mock.git
```

**Comment by alexmamonchik** [comment]
@aharbick I tried 2.2.0 from rubygems - it doesn't work. Gem doesn't have recent code. We going to release new version soon. I tested with code from repository - it works, #226 fixed your issue. I tested with StripeMock.start as you said.
@booleanbetrayal Can you check your test with last code from github repository?

**Comment by aharbick** [comment]
Great.  Thanks!  I'll watch for the new version.

**Comment by alexmamonchik** [comment]
@aharbick please, try https://rubygems.org/gems/stripe-ruby-mock/versions/2.2.1 and update stripe gem to new version

**Comment by aharbick** [comment]
that did it for me!  thanks @alexmamonchik !

**Comment by booleanbetrayal** [comment]
LGTM too @alexmamonchik !

**Comment by kathyonu** [comment]
@alexmamonchik @aharbick It is good to on gem again at 2.2.1. Thank you for your work on this. @booleanbetrayal what is LGTM ?

**Comment by booleanbetrayal** [comment]
"Looks good to me"  =]

**Comment by kathyonu** [comment]
@booleanbetrayal LIA :: Laughing I Am
