### ISSUE TITLE
Account.create returns value missing additional keys hash.

### ISSUE THREAD

**Issue by Mihail-K** [rebelidealist/stripe-ruby-mock#278]
`Stripe::Account.create country: 'CA', managed: true` returns a hash that's missing a 'keys' property, which is supposed to contain the secret and publishable keys.

https://stripe.com/docs/api/ruby#create_account

**Comment by andytcox** [comment]
+1 experiencing the same thing

**Comment by andytcox** [comment]
Some more info:
Gems
```
Rails 4.2
Ruby 2.1.5p273

stripe 1.31.0
stripe-ruby-mock 2.2.1
stripe_event 1.5.0
```

Looking through the code for mock accounts, it looks like this commit/merge may be the culprit - the new account mocks don't even reference the keys attribute. https://github.com/rebelidealist/stripe-ruby-mock/commit/cc254a45ea8c1174807b9f46845b8a2250cf5fda

**Comment by alexmamonchik** [comment]
@andytcox @Mihail-K try the last code from repo
