### ISSUE TITLE
Allow Stripe::Charge.create to take an id (like Stripe::Customer.create)

### ISSUE THREAD

**Issue by chipmunkgeek** [rebelidealist/stripe-ruby-mock#296]
`Stripe::Customer.create` can take an `:id` param, so that we can customize the customer id for testing purposes.  I find this helpful when I want an id to look like the one's that Stripe actually generates (beginning with `cus_`, instead of the stripe mock's default `test_cus_`).

It would similarly be helpful if `Stripe::Charge.create` could do the same thing.  I have validation rules to ensure that the id of a `Stripe::Charge` is valid, and an id like `test_ch_1` (which is the default format for stripe mock) isn't representative of what we would normally see as a response from the Stripe API.

```ruby
customer_id = 'cus_1234'
expect(Stripe::Customer.create(:id => customer_id).id).to eq(customer_id)  # This works.

charge_id = 'ch_1234'
params = {
  :id => charge_id,
  :customer => customer_id,
  :amount => 100,
  :currency => 'usd'
}
expect(Stripe::Charge.create(params).id).to eq(charge_id)  # This doesn't work (yet).
```

**Comment by chipmunkgeek** [comment]
Upon further research, I'm finding that supporting an `:id` param is actually part of Stripe's API for `Stripe::Customer.create` (even though this is hard to find in the Stripe API documentation).  You can create a custom id for a customer.  But, Stripe's API does *not* support a custom id for `Stripe::Charge.create`.

Because of this, I can understand if this issue is simply closed as `will not implement`.  But, I do still think it would be helpful if the charge id format is more reflective of what we would actually get from Stripe.

**Comment by alexmamonchik** [comment]
you can't know id of future charge. Maybe you should change test to:
```ruby
expect(Stripe::Charge.create(params).id).to match /(test_)?ch_\d+/
```
for example. I think you don't need to know exactly id of charge. You just need valid id.

**Comment by chipmunkgeek** [comment]
@alexmamonchik 

I think your suggestion is a good one.  I can adjust my tests accordingly to match like you have written above.
