### ISSUE TITLE
Bundle install failed with Stripe 1.33.1

### ISSUE THREAD

**Issue by shohey1226** [rebelidealist/stripe-ruby-mock#299]
Bundle install is failed..   Do you have any plan to release the new version for this? 

Thank you in advance.

```
Bundler could not find compatible versions for gem "stripe":
  In Gemfile:
    stripe-ruby-mock (~> 2.2.1) ruby depends on
      stripe (= 1.31.0) ruby

    stripe (1.33.1)
```

**Comment by alexmamonchik** [comment]
@shohey1226 stripe makes new releases too often. We have a lot of old opened issues, we didn't check stripe-ruby-mock with latest stripe yet, of course we going to do it soon.

**Comment by shohey1226** [comment]
@alexmamonchik yah, just checked stripe-ruby and see a lot of version changes, especially this year... I feel it's so hard to catch up..   anyway, thank you for your comment. I understand the situation.
