### ISSUE TITLE
NoMethodError: undefined method `external_accounts' for #<Stripe::Account:0x007fc131029168>

### ISSUE THREAD

**Issue by ryanfelton** [rebelidealist/stripe-ruby-mock#310]
For Stripe Managed Accounts, they now have the associated object "external accounts" that contain bank routing and bank account numbers.

https://stripe.com/docs/api#account_object-external_accounts

I would love to see external accounts supported by stripe-ruby-mock!

**Comment by Aeradriel** [comment]
It seems not to be only external accounts but all managed accounts. There is no `verification` field either.

**Comment by abmxer** [comment]
Any thoughts on how to handle this?

**Comment by Aeradriel** [comment]
If you are testing web hooks, you can create a json file containing a sample response with the name of your web hook (i.e. account.external_account.created) in spec/fixtures/stripe_web_hook. It will be automatically loaded by the gem.

I you want to test basics calls (such as `Stripe::Customer.create`), I do not think it is implemented yet. I will maybe contribute to the gem to fix it this week end if I can find some time. :smile:

**Comment by abmxer** [comment]
Actually, I'm trying to create an bank account. 

```
  1) StripeService Customer should update a managed account
     Failure/Error: account.external_accounts.create(:external_account => options)
     
     NoMethodError:
       undefined method `external_accounts' for #<Stripe::Account:0x0055ed8c2a17d0>
     # /usr/local/bundle/gems/stripe-1.50.0/lib/stripe/stripe_object.rb:271:in `method_missing'

```

I tried to redefine the ```external_accounts``` inside my test, but I was not able to. 

```
      module StripeMock
        def external_accounts=
        end

        def external_accounts
        end
      end
      Stripe::Account.extend StripeMock
```

Any thoughts on how to monkey patch this until there be an official support? 

Thanks!

**Comment by Aeradriel** [comment]
Well, I made a PR that was just merged to add external_accounts to account's hash and external_accounts webhooks.
Adding the whole external accounts logic will take a little more time considering the fact that I need to dive deeper into the code to fully understand the behaviour of the gem. I will start working on it tomorrow and I will notify you here when I'll be done with it. :)
