### ISSUE TITLE
Release 2.3

### ISSUE THREAD

**Issue by typeoneerror** [rebelidealist/stripe-ruby-mock#324]
Can you cut a release for 2.3 that includes the >= 1.3.1 stripe dependency:

https://github.com/rebelidealist/stripe-ruby-mock/commit/64b3e94c3b3d826859578aea289bd726aa6c8db0

**Comment by alexmamonchik** [comment]
@mindeavor please, make `2.2.3` I think?

**Comment by mindeavor** [comment]
Closed via 8706855a781dbb8bb52489580f1f0393bf6f240e
