### ISSUE TITLE
Something about the update in stripe-ruby from 1.41.0 to 1.42.0 breaks Subscription deletion in the test environment

### ISSUE THREAD

**Issue by JamesChevalier** [rebelidealist/stripe-ruby-mock#331]
[This](https://github.com/stripe/stripe-ruby/compare/ca7adcf8c80f646d883d9dec49f22f43bd469711...49382f7ac2ffb295ce8b4ff618724cfba8ad7f40) is a list of all the changes in [stripe-ruby](https://github.com/stripe/stripe-ruby) from 1.41.0 to 1.42.0

This is my model code to delete a Subscription in Stripe:

```
def remove_from_stripe
  stripe_customer     = Stripe::Customer.retrieve(account.stripe_customer_id)
  stripe_subscription = stripe_customer.subscriptions.retrieve(stripe_subscription_id)
  stripe_subscription.delete
rescue => error
  Rollbar.error(error, "Error while removing subscription from Stripe: #{error.message}")
  return { errors: ["Error while removing subscription from Stripe: #{error.message}"] }
end
```

This is my model rspec test:

```
describe 'interaction with stripe' do
  let(:subscription)  { create(:subscription) }
  let(:stripe_helper) { StripeMock.create_test_helper }
  before              { StripeMock.start }
  after               { StripeMock.stop }

  it 'responds to remove_from_stripe correctly' do
    stripe_plan     = stripe_helper.create_plan(amount: 0)
    stripe_customer = Stripe::Customer.create(email: 'person@place.com', card: stripe_helper.generate_card_token)
    account         = create(:account, stripe_customer_id: stripe_customer.id)
    plan            = create(:plan, stripe_plan_id: stripe_plan.id)
    subscription    = build(:subscription, account: account, plan: plan, stripe_subscription_id: nil)
    subscription_id = subscription.create_in_stripe(subscription.plan_stripe_plan_id)
    subscription.update_attribute(:stripe_subscription_id, subscription_id)
    subscription.reload
    expect(subscription.remove_from_stripe.id).to eq('test_su_4')
  end
end
```

I'm using stripe-ruby-mock version 2.2.3, and the above test succeeds with stripe version 1.41.0 & fails with stripe version 1.42.0

The failure is:

> 1) Subscription interaction with stripe responds to remove_from_stripe correctly
>    Failure/Error: expect(subscription.remove_from_stripe.id).to eq('test_su_4')
> 
>    NoMethodError:
>      undefined method `id' for "#<Stripe::Subscription:0x9ye4h27j20b1> JSON: {\n}".  HINT: The 'id' attribute was set in the past, however.  It was then wiped when refreshing the object with the result returned by Stripe's API, probably as a result of a save().  The attributes currently available on this object are:

I'm seeing that the response to my `stripe_subscription.delete` call is empty:

```
#<Stripe::Subscription:0x3ff642a08bec> JSON: {
}
```

This issue does not occur outside of the test environment. I have stripe-ruby-mock installed to only the test environment like:

```
group :test do
  gem 'stripe-ruby-mock'
end
```

So from what I can tell, the issue is with stripe-ruby-mock as opposed to stripe itself.

I haven't been able to figure out what the issue is, yet. Can anyone else spot it?

**Comment by alexmamonchik** [comment]
2.2.4 has been released just now. Here stripe dependency locked to `['>= 1.31.0', '< 1.42']`

**Comment by alexmamonchik** [comment]
soon we will cover updates from 1.42.0.

**Comment by chadoh** [comment]
@alexmamonchik glad to hear that 1.42.0 will be supported soon! Is there a separate issue for that, or should I subscribe to this issue to find out when it drops?

**Comment by alexmamonchik** [comment]
@chadoh please, create a new issue for that.
