### ISSUE TITLE
Unable to connect to stripe mock server (did you forget to run `$ stripe-mock-server`?)

### ISSUE THREAD

**Issue by ChrisCPO** [rebelidealist/stripe-ruby-mock#332]
When running a test calling ```@client = StripeMock.start_client``` in a Rspec before block

running  all this in a Rails engine.

```ruby

Waiting for StripeMock Server.....F

Failures:

  1) Subscription new user subscription user picks a plan
     Failure/Error: client = StripeMock.start_client
     StripeMock::ServerTimeoutError:
       Unable to connect to stripe mock server (did you forget to run `$ stripe-mock-server`?)
     # ./spec/features/subscriptions/new_subscription_spec.rb:6:in `block (3 levels) in <top (required)>'
```

**Comment by alexmamonchik** [comment]
can you use in your rspec:
``` ruby
before { StripeMock.start }
after { StripeMock.stop }
```

**Comment by ChrisCPO** [comment]
Thats not working, I'm trying to run the server for testing credit card transactions. Capybara blocks the api calls however, I don't think StripeMock is calling the local server.

**Comment by alexmamonchik** [comment]
please, provide example of spec

**Comment by ChrisCPO** [comment]
```ruby
feature "Subscription", js: true do
  feature "new user subscription" do
    it "user picks a plan" do
      current_user_helper(FactoryGirl.create(:user))
      plans = create_stripe_plans(:classic, :premium)
      visit "/scribe"

      within "#scribe_plan_1" do
        click_link "Subscribe"
      end

      fill_in "Card Number", with: visa_card
      fill_in "Expiration", with: future_date
      fill_in "CVC", with: "123"

      click_button "Submit Payment"
    end
  end
end
```

spec_helper.rb
```ruby
RSpec.configure do |config|
  config.before { StripeMock.start }
  config.after { StripeMock.stop }
end
```

**Comment by ChrisCPO** [comment]
The gem is acting as if I have live mode turned on. 
but I don't.

**Comment by alexmamonchik** [comment]
test of capybara but config for rspec. I didn't work with capybara, but can you put `StripeMock.start` direct to test?

**Comment by ChrisCPO** [comment]
I have tried that. What do you mean "test of capybara but config for rspec"?

thanks for your help btw

**Comment by alexmamonchik** [comment]
I see the doc by capybara. Looks like it is possible to write:
```ruby
feature "Subscription", js: true do

  before :each do
    StripeMock.start
  end

  feature "new user subscription" do
```
do you understand my idea? https://github.com/jnicklas/capybara#using-capybara-with-rspec

your example is capybara test. But you set config `config.before { StripeMock.start }` for rspec tests. I'm not sure that `before` in that place is working as you want. Let's detect that stripe-ruby-mock works - just put StripeMock.start to test.

**Comment by ChrisCPO** [comment]
ok stripe mock is working, added a StripeMock.create_test_helper
and then inspected it in pry and called create_plan one it which created a plan

**Comment by alexmamonchik** [comment]
nice. All you need is find right place for `StripeMock.start`. In some my rspec tests I use it in `before` callback for not in spec_helper.rb. I use it inside `describe`.

**Comment by ChrisCPO** [comment]
ok yea thanks for the help.

**Comment by AndreiMotinga** [comment]
👍   @ChrisCPO
