### ISSUE TITLE
Support stripe-ruby 1.42.0

### ISSUE THREAD

**Issue by chadoh** [rebelidealist/stripe-ruby-mock#335]
@alexmamonchik in https://github.com/rebelidealist/stripe-ruby-mock/issues/331#issuecomment-217494139 says that version 1.42.0 of stripe-ruby will be supported soon. This issue is to track progress on that effort.

**Comment by typeoneerror** [comment]
I'd be happy to work on this update. Should probably release 2.3 now and then make the Stripe subscriptions updates 2.4.

**Comment by mysmallidea** [comment]
I'm willing to help with this, but I'm brand new to the project and would need some guidance. What's the best way for me to contribute?

**Comment by alexmamonchik** [comment]
@mysmallidea welcome. 
1. fork this repository
2. execute tests
3. fix broken tests
4. send pull request

Also, I think you can discuss it in gitter - link in readme.

**Comment by mysmallidea** [comment]
Thanks, I did read the doc on contributing. After upgrading gem versions I was confronted with an avalanche of errors, so it's hard to even know where to start. Gitter is nice, but I don't see anyone in there talking about this issue. I'll try digging into the source code, but I'm not sure how much I'll be able to do.

**Comment by alexmamonchik** [comment]
@mysmallidea I understand. comment all lines https://github.com/rebelidealist/stripe-ruby-mock/blob/master/spec/support/stripe_examples.rb#L8-L31 except one and exec test. You will see less errors and will know where is the start. Also, most of errors are the similar. You fixed one error it will be solved in another file.

**Comment by typeoneerror** [comment]
@mysmallidea yeah, I don't think gitter is being used any longer. FYI, @alexmamonchik, I did reach out there about being added as a contributor, but never heard back. still happy to help release!

**Comment by adbjesus** [comment]
Any update on this? I can try to pick it up this weekend if nobody else is on it already.

**Comment by typeoneerror** [comment]
haven't started, so have at it. be happy to assist/review

**Comment by mysmallidea** [comment]
I have not had a chance to work on it, sorry.

**Comment by alexmamonchik** [comment]
@chadoh @typeoneerror @mysmallidea , let's review #343 and give your comments. Thanks @adbjesus for help
