### ISSUE TITLE
Release 2.3 or 2.2.5

### ISSUE THREAD

**Issue by typeoneerror** [rebelidealist/stripe-ruby-mock#336]
Just updated to 2.2.4, but the balance transaction mocking isn't included in the release. Looks like potentially 2.2.4 was cut before the merge based on the tag being 2 commits behind master (https://github.com/rebelidealist/stripe-ruby-mock/releases/tag/v2.2.4)? Should we release 2.3 here since this isn't a patch release?

**Comment by alexmamonchik** [comment]
look at this https://github.com/rebelidealist/stripe-ruby-mock#versioning-system
As I understand your changes should be in `2.2.x`. But Stripe updates #335 `2.3.0`. Sorry, your PR wasn't included to `2.2.4` what if we include it in `2.2.5` ?

**Comment by typeoneerror** [comment]
@alexmamonchik ah, okay, I was thinking of semantic versioning for the gem itself. this is pretty different style. in this case, 2.2.5 release would make sense for the BalanceTransaction API addition.
