### ISSUE TITLE
customer.subscriptions.retrieve throws TypeError

### ISSUE THREAD

**Issue by PureSin** [rebelidealist/stripe-ruby-mock#348]
On stripe-ruby-mock `2.3.0` and stripe 1.43.0.

Calling `sub = customer.subscriptions.retrieve(sub_id)` throws:

```
TypeError: no implicit conversion of Symbol into Integer
from /Users/kelvinma/Work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/stripe-ruby-mock-2.3.0/lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb:6:in `[]'
```

Looking inside `retrieve_customer_subscription` method. I see its returning customer as an array with index 0 being `:customer`, 1 being the id, 2 being the actual customer object.
 
```
customer = :customer, $1, customers[$1]
=> [:customer,
 "test_cus_3",
 {:email=>"user0@example.com",
  :description=>"an auto-generated stripe customer data mock",
```

vs calling customers[$1] directly returns the customer object

```
customers[$1]
=> {:email=>"user0@example.com",
 :description=>"an auto-generated stripe customer data mock",
 :object=>"customer",
```

which the next line `get_customer_subscriptions` 
`customer[:subscriptions][:data].find{|sub| sub[:id] == sub_id }` then errors with `TypeError: no implicit conversion of Symbol into Integer` since `customer` is an array here. 

Has anyone else encountered this error?

**Comment by jentzheng** [comment]
Yes it throw error on latest Rails 5, stripe-ruby-mock (2.3.0), stripe (1.43.0)
```
customer.subscriptions.retrieve('test_su_4')
*** TypeError Exception: no implicit conversion of Symbol into Integer
```

**Comment by AxelTheGerman** [comment]
I am getting the same error after trying to upgrade from `2.2.4` (also upgrading stripe from `1.41.0` to `1.43.0`)

I was hoping to finally be able to upgrade the stripe gem, but not if it breaks my tests. Any help is highly appreciated.

**Comment by sublimecoder** [comment]
I'm getting the same error. Looks like the issue in this line.  
https://github.com/rebelidealist/stripe-ruby-mock/blob/master/lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb#L6

**Comment by AndreiMotinga** [comment]
I'm still getting it

**Comment by PureSin** [comment]
@AndreiMotinga Its merged to master but haven't been released in a new version of the Gem yet. Either wait for a new release `2.3.1` or change your Gemfile to directly pull from this repo on master.
