### ISSUE TITLE
updating subscription's plan > "no such customer" error

### ISSUE THREAD

**Issue by ChrisCPO** [rebelidealist/stripe-ruby-mock#354]
Updating a subscription's plan via the stripe docs way still results in a 'no such customer error

Rails.version "4.0.13"
stripe-ruby-mock-2.0.1
docs:
```ruby
subscription = Stripe::Subscription.retrieve({SUBSCRIPTION_ID})
subscription.plan = {PLAN_ID}
subscription.save
```
my code:

      stripe_sub = user.subscription.stripe_self
      stripe_sub.plan = plan_id
      stripe_sub.save
error:

Stripe::InvalidRequestError:
No such customer: test_cus_3/subscriptions/test_su_4

This works when live testing is set to true, but not when mocking.

**Comment by ChrisCPO** [comment]
This is also happening with deleting a subscription.

**Comment by alexmamonchik** [comment]
@ChrisCPO what is the version of stripe do you use?

**Comment by ChrisCPO** [comment]
@alexmamonchik 1.39

**Comment by alexmamonchik** [comment]
@ChrisCPO fixed for `subscription.delete` method. Please, check for update method - I can't reproduce it. Also, try `StripeMock.toggle_debug(true)` after StripeMock init and share result

**Comment by ChrisCPO** [comment]
@alexmamonchik  cool thank you
