### ISSUE TITLE
Undefined method card for Stripe::Charge

### ISSUE THREAD

**Issue by phillipp** [rebelidealist/stripe-ruby-mock#381]
Hi,
I just added stripy-ruby-mock to my project and get the following error when displaying the charge:

```
     NoMethodError:
       undefined method `card' for #<Stripe::Charge:0x00000009cb7830>
```

Stripe's charge object has the card attached to it. The mock charge does not. Is this expected or a bug?

**Comment by alexmamonchik** [comment]
looks like you are using the old API version. In newest gem we use API api-2014-06-17 version. Charge object has `source` method https://stripe.com/docs/api#charge_object

**Comment by phillipp** [comment]
Oh, thanks, I haven't thought about that :face_with_head_bandage:
