### ISSUE TITLE
Stripe 2.0.0 released, updated dependencies

### ISSUE THREAD

**Issue by cannikin** [rebelidealist/stripe-ruby-mock#410]
Stripe released version 2.0.0 of the gem recently with the following changes:

* Drop support for Ruby 1.9
* Allow HTTP client that makes Stripe calls to be configured via Faraday
* Drop RestClient
* Switch to OpenAPI 2.0 spec and generated fixtures in test suite
* Switch to Webmock in test suite

`stripe-ruby-mock` has us locked into `~> 1.31`. Any plans to update that dependency? If the 1.9 support is a concern maybe fork the current version of this gem and have it retain 1.9 support while this one moves forward with the `stripe` gem itself?

**Comment by thiagoramos23** [comment]
Is anyone getting this so I can help?

**Comment by nfm** [comment]
One reason the `stripe` gem switched to Faraday is to make adding request/response middleware easier. So `stripe-ruby-mock` could hook into attempted HTTP requests and return data in a much nicer way. I think that would be a pretty significant rewrite of how this gem works internally though.
