### ISSUE TITLE
Retrieve Balance

### ISSUE THREAD

**Issue by garrettqmartin8** [rebelidealist/stripe-ruby-mock#418]
When using `Stripe::Balance.retrieve()`, I get this warning when running my tests: `[StripeMock] Warning : Unrecognized endpoint + method : [get /v1/balance]`

I can work on submitting a PR if people would find it helpful to have that mocked!

**Comment by alexmamonchik** [comment]
@garrettqmartin8 sure! Please, submit your PR, we need your help. Thanks
