### ISSUE TITLE
Negative Transfer amount should raise exception

### ISSUE THREAD

**Issue by mwgalloway** [rebelidealist/stripe-ruby-mock#419]
The Stripe API only allows Stripe::Transfer.create to succeed if the amount passed in is a positive integer, passing in anything else raises an exception. The mock currently let's a negative transfer value slide by.  I'm happy to submit a PR if people would like to see this implemented.

**Comment by alexmamonchik** [comment]
@mwgalloway please, check attached commit. Looks like the mock doesn't allow negative amount.
