### ISSUE TITLE
Is the fee on new_balance_transaction correct?

### ISSUE THREAD

**Issue by arthurnn** [rebelidealist/stripe-ruby-mock#432]
HI 👋 

First of all thanks a lot for the gem. ❤️ 

I have a question and thought if it is a bug or not. I am using stripe ruby gem with the Connect(managed account) on the backend.
So in my App I create a charge, and after I get the balance_transaction for that charge to generate an invoice. On the balance transaction, I use the amount and net amount.
When testing my app with this gem, I found that the balance transaction net amount was not matching with the application fee I was passing to the charge. Looking at the gem, I found [this line](https://github.com/rebelidealist/stripe-ruby-mock/blob/dc0889772a812646ef2cdd9f26b63e13c1e42f6b/lib/stripe_mock/instance.rb#L165) where I see the fee on the balance txn is generated on the fly, and not using the `application_fee` from the charge. Is that a bug, or I am miss understanding the stripe connect API.

I think with something like this you can simulate what I am describing above:
```ruby
amount = 22000
fee_percentage = 20 # 20%
fee = Integer((amount * (fee_percentage/100.0) ).round)

dest_account = Stripe::Account.create(email: 'vendor@email.com', transfers_enabled: true)
customer = Stripe::Customer.create(email: 'customer@email.com', card: stripe_helper.generate_card_token)

charge = Stripe::Charge.create(
  amount: amount,
  currency: 'cad',
  customer: customer.id,
  destination: dest_account.id,
  application_fee: fee
)

balance_txn = Stripe::BalanceTransaction.retrieve(charge.balance_transaction)
expect(balance_txn.amount).to eq(amount)
expect(balance_txn.net).to eq(amount - fee)
```

thanks

**Comment by alexmamonchik** [comment]
Hi @arthurnn . thank you for report. Looks like a bug. Unfortunately, we don't have enough active committers. Will be fine if so experienced open source developer like you helps us with this issue. Or please, wait for someone. We will solve it.

**Comment by MaicolBen** [comment]
I made a PR solving the issue #572!
