### ISSUE TITLE
Support "Payouts" now that Transfers have split

### ISSUE THREAD

**Issue by JackGalore** [rebelidealist/stripe-ruby-mock#446]
Stripe recently split the concept of "Transfers" which encompassed transfers between bank accounts and cards _and_ transters between managed accounts. They've now split this so that *Transfers* will mean moving money between Stripe accounts as part of Connect and will be represented by `/v1/transfers`. *Payouts* will mean moving money from Stripe to your bank account or debit card and will be represented by `/v1/payouts`. See this page for more info: https://stripe.com/docs/transfer-payout-split

**Comment by arthurnn** [comment]
Added support to it here https://github.com/rebelidealist/stripe-ruby-mock/pull/483
