### ISSUE TITLE
Version 2.5 not released as instructed in the README

### ISSUE THREAD

**Issue by andela-echigbo** [rebelidealist/stripe-ruby-mock#463]
In this commit: https://github.com/rebelidealist/stripe-ruby-mock/commit/275affdd6e2f17b79660586abf886cc5b9e31f47
@alexmamonchik changed the version specified in Gemfile to **2.5** but this version has not being released (at least not to Rubygems) and the _version_ file in the master branch still says **2.4.1**

**Comment by alexmamonchik** [comment]
@andela-echigbo Hi. Only @gilbert can do release. I don't have access to Rubygems.

**Comment by andela-echigbo** [comment]
Okay, make sense @alexmamonchik. But the master branch still says 2.4.1. Even the _release-2.5_ branch. Or has the updates not been pushed to Github?

**Comment by gilbert** [comment]
@alexmamonchik Do you want to bump the current master to 2.5.0?

**Comment by andela-echigbo** [comment]
Hey, guys! Any update on bumping and releasing v2.5.0 as already instructed in the Readme? cc @gilbert & @alexmamonchik

**Comment by gilbert** [comment]
Just need a specific instruction from @alexmamonchik

**Comment by alexmamonchik** [comment]
@gilbert let's bump the current master to 2.5.0 and release new version of gem.

**Comment by gilbert** [comment]
Released via 0cc06eb8675349601e72da64f66690b0eb3a809a

**Comment by andela-echigbo** [comment]
Hey! Thank you for releasing this. I feel more relaxed now installing v2.5.0 from RubyGems source 🙂
