### ISSUE TITLE
Error when mocking Subscription items instead of plan

### ISSUE THREAD

**Issue by sbounmy** [rebelidealist/stripe-ruby-mock#464]
Valid Stripe request :
```ruby
Stripe::Subscription.create(customer: 'any-id', items: ['sleep_monthly', 'work_monthly'])
```
but when mocking it raises :
```ruby
Stripe::InvalidRequestError: (Status 404) No such plan: >
```

I believe this is due to https://github.com/rebelidealist/stripe-ruby-mock/blob/7cc2de9241b194c1dbf75d90f184614476047c79/lib/stripe_mock/request_handlers/customers.rb#L36
So this mock works properly :
```ruby
Stripe::Subscription.create(customer: 'any-id', plan: 'sleep_monthly', items: ['sleep_monthly', 'work_monthly'])
```

According to Stripe API : plan is optional when using items. Could we remove plan assertion in stripe-ruby-mock ?

**Comment by nlively** [comment]
See also: #429

**Comment by alexmamonchik** [comment]
@nlively please, check the last update. I think it solves your case

**Comment by sbounmy** [comment]
hey @alexmamonchik thanks for the PR !
It works but are subscription items fully supported like updates cc #469 ?
 
```ruby
sub = Stripe::Subscription.create(customer: 'any-id', items: [{ plan: 'sleep_monthly', quantity: 1}, {plan: 'work_monthly', quantity: 1}])
sub.items.each do |item|
  item.quantity = 100
  item.save #raise the following error
end
```

raises
```ruby
raise NoMethodError Exception: undefined method `data' for {}:Hash
```

**Comment by alexmamonchik** [comment]
yes, because no `save` method for `SubscriptionItem` object. #429

**Comment by muaziqbal55** [comment]
product = Stripe::Product.create(name: 'Muaz')
it gives me following as expected 
#<Stripe::Product:0x4e84 id=test_prod_2> JSON: {
  "id": "test_prod_2",
  "active": true,
  "created": 1556896214,
  "livemode": false,
  "metadata": {},
  "name": "Muaz",
  "statement_descriptor": "PRODUCT",
  "type": "service",
  "updated": 1556918200
}
but when I use this product in creating a price as follows it gives me error:
 --undefined method `data' for {}:Hash)
price = Stripe::Price.create(unit_amount: self.price * 100, currency: 'usd', product: product)

[StripeMock] Warning : Unrecognized endpoint + method : [post /v1/prices]
[StripeMock] params: {:unit_amount=>10000, :currency=>"usd", :product=>#<Stripe::Product:0x4e84 id=test_prod_2> JSON: {
  "id": "test_prod_2",
  "object": "product",
  "active": true,
  "created": 1556896214,
  "livemode": false,
  "metadata": {},
  "name": "Muaz",
  "statement_descriptor": "PRODUCT",
  "type": "service",
  "updated": 1556918200
}}
Traceback (most recent call last):
        1: from (irb):10
NoMethodError (undefined method `data' for {}:Hash)

**Comment by TastyPi** [comment]
@muaziqbal55 firstly, please don't comment on issues that have been closed for 5 years, it's better to start a new one.

Second, you should be passing the ID of the product, not the product itself

```ruby
Stripe::Price.create(unit_amount: self.price * 100, currency: 'usd', product: product.id)
```

**Comment by muaziqbal55** [comment]
@TastyPi  sorry I will start a new issue next time.
passing the product id gives the same error
infact it is not even letting me do Stripe::Price.create, while I am able to do do Stripe::Product.create or Stripe::Product.create and getting response in return from webmock
 
it gives this warning on price only
[StripeMock] Warning : Unrecognized endpoint + method : [post /v1/prices]
Does stripe mock covers Stripe::Price??
