### ISSUE TITLE
Using stripe-ruby v3.5.1: Not responding when called inline with Sidekiq

### ISSUE THREAD

**Issue by espen** [rebelidealist/stripe-ruby-mock#504]
v3.5.1 fixes an issue with [thread safety](https://github.com/stripe/stripe-ruby/issues/590). For some reason this results in no response when calling Stripe commands after upgrading to this version (or newer). It just stops (doesn't execute beyond Stripe calls). I am only able to replicate this issue when running Stripe commands from integration tests with code in a Sidekiq job which I am running as inline (Sidekiq::Testing.inline!).

**Comment by cgunther** [comment]
I believe I have a fix for this in #518. Could you test with my branch and see if that resolves the issue for you?
