### ISSUE TITLE
StripeMock and Rails System Tests

### ISSUE THREAD

**Issue by johnmaxwell** [rebelidealist/stripe-ruby-mock#516]
First of all, thank you for stripe-ruby-mock. It has saved me a lot of time and led to more complete test coverage across several projects that use Stripe.

I'm having difficulty getting StripeMock working with the Capybara-based testing that underpins Rails system tests. There are several pieces at play that are contributing to the issue, and I recognize that this difficulty doesn't lie completely with stripe-ruby-mock. I'm primarily posting this issue with the hopes of finding some guidance to resolving this issue.  Here are the versions that I'm using.

* stripe-ruby-mock (2.5.2)
* stripe (3.9.2)
* rails (5.1.4)

The core of the issue seems to boil down to this:

1. Stripe implements per-thread Stripe::StripeClient.active_client as of https://github.com/stripe/stripe-ruby/pull/591
2. The test server started by Rails System Tests run in a separate thread pool under Puma.
3. StripeMock.start and StripeMock.start_client intercept calls Stripe::StripeClient.active_client of the current thread but not the threads of the spawned test server. 

So even if I start StripeMock with StripeMock.start or StripeMock.start_client in the test file, the puma-based test server running in another thread doesn't have same StripeClient with the intercepted `execute_request` method. 

At present, it looks like the StripeClient is stored in either the stripe_client or stripe_client_default_client fiber-local variables. Would the idea be to start enable StripeMock in the integration test file and then overwrite one of those fiber-local variables in the puma-based test server? If so, any guidance for how to do this? Or am I off-base here?

**Comment by nfm** [comment]
I don't have too much to add, but I also ran into this issue today and can confirm you're on the right track @johnmaxwell. I've downgraded to stripe 3.5.0 as a workaround for now.

If you haven't run into this already, be aware that if you're using any of Stripe's JS libraries to handle cards they're also difficult to mock. They'll send the card details to Stripe directly and return a real token, which stripe-ruby-mock then needs to be able to deal with. More info in https://github.com/rebelidealist/stripe-ruby-mock/issues/360.

**Comment by cgunther** [comment]
I believe I have a fix for this in #518. Could you test with my branch and see if that resolves the issue for you?

**Comment by nfm** [comment]
@cgunther I've tested #518 in our app with stripe 3.9.2 and can confirm that our test suite passes. It fails on stripe 3.9.2, stripe-ruby-mock 2.5.2, due to the webserver thread actually hitting the Stripe API and creating customers that stripe-ruby-mock doesn't know about in the test thread.

**Comment by johnmaxwell** [comment]
@cgunther Yes! That fixes the reported issue.

**Comment by johnmaxwell** [comment]
Fixed with merged #518
