### ISSUE TITLE
Received unkown parameter: current_period_end

### ISSUE THREAD

**Issue by JustinasDaugela** [rebelidealist/stripe-ruby-mock#540]
I'm trying to write specs for our Stripe webhooks, one of which checks for `current_period_end` in the Stripe::Subscription, in order to say when the subscription should stop.

However

```
      Stripe::Subscription.create({
        customer: "cid",
        current_period_end: Time.now.to_i,
      })
```

returns

```
     Stripe::InvalidRequestError:
       Received unknown parameter: current_period_end
```

The Stripe API shows this attribute under the Subscription object: https://stripe.com/docs/api?lang=ruby#subscription_object

**Comment by iCreateJB** [comment]
This appears to be an attribute on the subscription object, not one set upon creating a subscription. 

What you would want to do to satisfy this is create a plan with an interval in which you can predict the end and then subscribe a customer to that.
