### ISSUE TITLE
Tests failing - too many open files

### ISSUE THREAD

**Issue by s2t2** [rebelidealist/stripe-ruby-mock#553]
Hey, I'd like to contribute back to this library, and I'm trying to [run rspec](https://github.com/rebelidealist/stripe-ruby-mock/wiki/Implementing-a-New-Behavior#running-the-tests) and most tests are failing. Is there any context behind this? Please advise. Thanks!

**Comment by alexmamonchik** [comment]
please, read [this](https://github.com/rebelidealist/stripe-ruby-mock/wiki/Implementing-a-New-Behavior). I saw your message in the chat but I have never seen a similar error, sorry.

**Comment by s2t2** [comment]
I realize more details would be helpful 😸. After cloning/pulling from master, I'm seeing 334 errors total, the most prevalent being:

```
Failure/Error: Unable to find matching line from backtrace
     SocketError:
       getaddrinfo: nodename nor servname provided, or not known
     Shared Example Group: "Charge API" called from ./spec/support/stripe_examples.rb:14
     # ./lib/stripe_mock/client.rb:8:in `initialize'
     # ./lib/stripe_mock/api/client.rb:12:in `new'
```

I thought maybe running `bin/stripe-mock-server` in another window might satisfy socket-related expectations, but still seeing 331 failures.

Is there a specific version of the stripe gem I should be using?

```sh
gem list stripe
#> stripe (3.26.1, 3.19.0)
```

Separately, also seeing a lot of api-related "Missing required param" failures like this (which could be due to version differences?):

```sh
 Failure/Error: plan = Stripe::Plan.create(
     Stripe::InvalidRequestError:
       Missing required param: product.
     Shared Example Group: "Plan API" called from ./spec/support/stripe_examples.rb:23
     # ./lib/stripe_mock/request_handlers/validators/param_validators.rb:15:in `block in validate_create_plan_params'
```

Separately, I'm seeing these too:

```sh
 Failure/Error: Thread.new { Stripe::StripeClient.active_client.execute_request(:xtest, '/', api_key: 'abcde') }.join # no error
     Errno::EMFILE:
       Too many open files - uname -a 2>/dev/null
```

**Comment by s2t2** [comment]
Seeing [this](https://github.com/rebelidealist/stripe-ruby-mock/#requirements) now. Trying `stripe >= 2.0.3`...

**Comment by s2t2** [comment]
OK, so, I was able to resolve this issue. It was due to my local computer's memory configurations.

```sh
ulimit -n 
#> 256 (apparently not enough memory/processing power to handle the server specs
ulimit -n -1024 # (better, but also not high enough)
ulimit -n 2500 # SUFFICIENT TO RUN SERVER SPECS!
```

NOTE: that when you change the `ulimit`, you can only change once per terminal window, and the changes are only applicable to that terminal window. So if you try to set a `ulimit` that ends up being too low, you need to open up a new terminal window and try again.

h/t: https://stackoverflow.com/questions/40597488/ruby-too-many-open-files-rb-sysopen
