### ISSUE TITLE
#generate_card_token default expiry date for valid cards expired

### ISSUE THREAD

**Issue by xavierperera** [rebelidealist/stripe-ruby-mock#558]
#generate_card_token uses a fixed month and year, September 2018. We already passed that date so
credit cards generated with default parameters will fail.

I solved it by replacing '2018' with (Time.now.year + 5) here:

https://github.com/rebelidealist/stripe-ruby-mock/blob/033651cb461b541ca5b4d30ca55ca7ae4001203a/lib/stripe_mock/test_strategies/base.rb#L19

I consider it worth to check if there are any other fixed dates around that might cause problems in the future.

**Comment by jjwyse** [comment]
Thanks for fixing this, much appreciated.  We're running into this issue now - is there any plan to cut a new release of this gem to pull in this fix ☝️?  Thanks again!

**Comment by alexmamonchik** [comment]
@jjwyse [2.5.5](https://rubygems.org/gems/stripe-ruby-mock/versions/2.5.5)
