### ISSUE TITLE
On the subsciption under the discount there is no `end` date 

### ISSUE THREAD

**Issue by lefterisnik** [rebelidealist/stripe-ruby-mock#562]
Based on the Stripe API, the discount field on the subscription object should contain an discount object which should have the following fields:

https://stripe.com/docs/api#discounts

But based on the code on line https://github.com/rebelidealist/stripe-ruby-mock/blob/master/lib/stripe_mock/request_handlers/subscriptions.rb#L63 there is no code to generate the other fields.

Please could you have a look?

**Comment by iCreateJB** [comment]
Appears to be present, but there's a condition around it's presence. 

```
        customer[:discount][:end] = (DateTime.now >> coupon[:duration_in_months]).to_time.to_i  if coupon[:duration].to_sym == :repeating && coupon[:duration_in_months]
```

**Comment by lefterisnik** [comment]
Thanks @iCreateJB
