### ISSUE TITLE
support multiple subscriptions on customer object

### ISSUE THREAD

**Issue by jhsu** [rebelidealist/stripe-ruby-mock#58]
https://support.stripe.com/questions/whats-new-with-multiple-subscriptions-per-customer-january-2014

their blog post: https://stripe.com/blog/multiple-subscriptions

**Comment by alexmamonchik** [comment]
closed by 1fd490818e2ad575f45ab9a863e8d749521a63d9

**Comment by jhsu** [comment]
:clap:
