### ISSUE TITLE
Payment Intents and Methods APIs (SCA)

### ISSUE THREAD

**Issue by Jensenks** [rebelidealist/stripe-ruby-mock#618]
Is anyone working on the new SCA ready APIs? 

**Edit:** Looks like it's getting worked on by contributors here: https://github.com/FarmDrop/stripe-ruby-mock/commits/payment_method

It would be great to have these added to stripe-ruby-mock before the [Strong Customer Authentication](https://stripe.com/docs/strong-customer-authentication) regulation comes into effect on September 14, 2019.

The APIs include:
[Stripe Payment Intents API](https://stripe.com/docs/payments/payment-intents)
[Stripe Payment Methods API](https://stripe.com/docs/payments/payment-methods)

**Comment by ashkan18** [comment]
Opened a PR to add support for it 🤞

**Comment by ashkan18** [comment]
this adds support for more SCA use cases https://github.com/rebelidealist/stripe-ruby-mock/pull/622
