### ISSUE TITLE
SetupIntent API

### ISSUE THREAD

**Issue by renchap** [rebelidealist/stripe-ruby-mock#630]
In addition to the currently worked-on PRs for `PaymentIntent` & `PaymentMethods`, it would be great to have support for the [`SetupIntent` object](https://stripe.com/docs/api/setup_intents).
It is very similar to `PaymentIntent` but simpler.

**Comment by andreaslillebo** [comment]
I've already got `SetupIntent` working on a fork. I'll submit a pull request adding support for it as soon as `PaymentMethods` (#623) gets merged, since [`Confirming a SetupIntent`](https://stripe.com/docs/api/setup_intents/confirm) expects a `PaymentMethod`.
