### ISSUE TITLE
post /v1/checkout/sessions is not supported

### ISSUE THREAD

**Issue by doutatsu** [rebelidealist/stripe-ruby-mock#635]
I've switched to using new [Checkout API](https://stripe.com/docs/payments/checkout) to become compliant with SCA. So I had to change which API I am using, which is now `Stripe::Checkout::Session`. Those endpoints though are not supported by the gem at the moment.

```rb
    session = Stripe::Checkout::Session.create(
      customer: customer_id,
      payment_method_types: ['card'],
      submit_type: "donate",
      line_items: [{
        name: 'Donation',
        description: 'Thank you for donating!',
        amount: params[:amount],
        currency: 'USD',
        quantity: 1,
      }],
      success_url: dashboard_events_url,
      cancel_url: dashboard_events_url,
    )
```

**Comment by doutatsu** [comment]
Bump for this issue?

**Comment by aleatham** [comment]
Would love to see this supported. Looks like there was some work done already: https://github.com/rebelidealist/stripe-ruby-mock/pull/648
