### ISSUE TITLE
Cannot apply a coupon when creating a subscription

### ISSUE THREAD

**Issue by noctivityinc** [rebelidealist/stripe-ruby-mock#79]
When doing the following:

    plan_opts =  {:plan=>"Designer25", :coupon=>"WECORA5D"}
    subscription = customer.subscriptions.create(plan_opts)

the return is:

    #<Stripe::Subscription:0x3fd8c8007914 id=test_su_4> JSON: {
      "id": "test_su_4",
      "current_period_start": 1395759679,
      "current_period_end": 1398438079,
      "status": "active",
      "plan": "Designer25",
      "cancel_at_period_end": false,
      "canceled_at": null,
      "ended_at": null,
      "start": 1308595038,
      "object": "subscription",
      "trial_start": null,
      "trial_end": null,
      "customer": "test_cus_3",
      "quantity": 1
     }

when it should include a ```discount``` object representing the coupon.  Without it we cannot test subscriptions that are charged with discount.

Here are the docs - https://stripe.com/docs/api#create_subscription

Thanks.

**Comment by hcarver** [comment]
I actually did some of the work for this in [my fork](https://github.com/hcarver/stripe-ruby-mock) but that code doesn't actually apply the coupon yet - it just accepts it and returns it.

**Comment by alexmamonchik** [comment]
@noctivityinc, @hcarver  fixed.
